"""empty message

Revision ID: 7f4a5e9366d2
Revises: 805de247dc58
Create Date: 2020-02-11 19:00:37.296909

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '7f4a5e9366d2'
down_revision = '805de247dc58'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('posts',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('title', sa.String(length=140), nullable=True),
                    sa.Column('slug', sa.String(length=140), nullable=True),
                    sa.Column('body', sa.Text(), nullable=True),
                    sa.Column('time_stamp', sa.DateTime(), nullable=True),
                    sa.Column('user_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_posts_time_stamp'), 'posts', ['time_stamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_posts_time_stamp'), table_name='posts')
    op.drop_table('posts')
    # ### end Alembic commands ###
